### ISSUE TITLE
Add Author Contributions Template

### ISSUE THREAD

**Issue by jmburges** [LKWLaLa/story-mache#1]
When I click on an authors name on the story show page I want to be taken to a page that lists all of the contributions that Author made. The url should be `/authors/<AUTHOR NAME>`. 

On that page I want all of the contributions, as well as when and link to view the whole story

**Comment by LKWLaLa** [comment]
@jmburges :  Ok!  Feature has been implemented from Rails to Angular.  Will close this issue pending your review.
